### ISSUE TITLE
add support for video content?

### ISSUE THREAD

**Issue by phavx** [sahib/glyr#57]
Hi there (und Grüße aus FfM),

I'm pretty happy with how glyr's working, thanks for that. Unfortunately, I haven't yet found a tool which can reliably do the same for video (movies, tvshows) as glyr is doing for music. Thus I'd like to ask if you'd be interested extending glyr to a (pretty much) one stop solution for both audio & video?

So specify f.e. "--type={show,movie}" and then selectively get things like original title, airdate, plot, etc. from tvdb, imdb, etc.

Thanks for consideration(alternatively I'm happy with some links to other projects, too, of course).

**Comment by sahib** [comment]
Hi, 

Movies and Shows are not in glyr's reach, Sorry. There is however a library called libhugin that was developed as a "glyr-for-movies" by a friend. Not sure how well it is working right now. But I guess you're better off by asking the original author. As far as I know it is scheduled for a rewrite currently.

You can find it here:

https://github.com/qitta/libhugin

**Comment by phavx** [comment]
Thanks for the hint, I'll check it out.

(close at will or leave it open in case you change your mind ;) )
