### ISSUE TITLE
--write option doesn't work

### ISSUE THREAD

**Issue by cassiel74** [sahib/glyr#58]
despite using 
--write null 
the output is being displayed.

Version 1.0.6 (Raving Raven) on debian jessie

**Comment by sahib** [comment]
```--write null``` just disables writing the output file. You want ```-v 0``` to hide the output.

**Comment by cassiel74** [comment]
ok, thought ```-v``` was stricly debug related

another thing, the first line of the lyrics is merged with some javascript code:

```');var c=function(){cf.showAsyncAd(opts)};if(window.cf)c();else{cf_async=!0;var r=document.createElement("script"),s=document.getElementsByTagName("script")[0];r.async=!0;r.src="//srv.tonefuse.com/showads/showad.js";r.readyState?r.onreadystatechange=function(){if("loaded"==r.readyState||"complete"==r.readyState)r.onreadystatechange=null,c()}:r.onload=c;s.parentNode.insertBefore(r,s)};}})();"Ground Control to Major Tom
Ground Control to Major Tom
Take your protein pills and put your helmet on```

any hint on how to remove js "garbage"? should I use sed or what?

PS I am writing a quite simple shell script to use with cmus

**Comment by sahib** [comment]
That's a bug in some provider then. Please post your full commandline.

**Comment by cassiel74** [comment]
```
glyrc lyrics -n 1 -a "$a" -t "$t" --write stdout -v 0
```

**Comment by sahib** [comment]
I need the concrete artist and title where this happens.

**Comment by cassiel74** [comment]
'david bowie'
'space oddity'

but it happens with every request... at least the ones while I was testing

**Comment by sahib** [comment]
I was asking because I need to determine the buggy provider. I can't 
reproduce the issue here, but remember that I fixed something like this 
in the highest rated lyrics provider in 
https://github.com/sahib/glyr/commit/530e91963221eb299e6b123e7fdb4a692cc689e0.


Can you compile glyr from git and check if it happens there?

**Comment by cassiel74** [comment]
yep! The issue is fixed in git

**Comment by sahib** [comment]
Okay, good. I will do a release then, might take some time to get into your distribution though.

**Comment by cassiel74** [comment]
solved with sed here but unfortunately I believe this fix won't get into jessie release (freeze now).
