### ISSUE TITLE
lib/stringlib.c, ctype(3) usage fixes

### ISSUE THREAD

**Issue by iamleot** [sahib/glyr#61]
Hello Chris and the entire glyr community,
some days ago I updated the [audio/glyr](http://pkgsrc.se/audio/glyr)
package in [pkgsrc](http://www.pkgsrc.org). While there I saw that we have a
local and trivial patch that can be pushed upstream. Basically it just fixes the
[ctype(3)](http://netbsd.gw.com/cgi-bin/man-cgi?ctype+3+NetBSD-current).

I will attach it here, if it can't be easily handled via GitHub issues I can
send you a private email containing it.

Thank you for the attention and for this great piece of software!
L.

------------------8<-------------------8<-------------------8<------------------
$NetBSD: patch-lib_stringlib.c,v 1.1 2014/09/11 06:45:45 dholland Exp $

Use <ctype.h> correctly.

--- lib/stringlib.c~	2014-02-08 11:06:45.000000000 +0000
+++ lib/stringlib.c
@@ -927,8 +927,8 @@ static gchar * trim_in_text (gchar * str
 
         for (gsize it = 0; it < str_len; it++)
         {
-            gboolean is_space = isspace (string[it]);
-            gboolean is_lfeed = !isblank (string[it]) && is_space;
+            gboolean is_space = isspace ((unsigned char)string[it]);
+            gboolean is_lfeed = !isblank ((unsigned char)string[it]) && is_space;
 
             lfeed_ctr = (is_lfeed) ? lfeed_ctr + 1 : 0;
             space_ctr = (is_space) ? space_ctr + 1 : 0;
@@ -1011,7 +1011,7 @@ void trim_copy (gchar *input, gchar *out
     gchar c;
 
     /* skip spaces at start */
-    while (input[0] && isspace (*input) )
+    while (input[0] && isspace ((unsigned char)*input) )
     {
         ++input;
     }
@@ -1023,7 +1023,7 @@ void trim_copy (gchar *input, gchar *out
         c = * (output++) = * (input++);
 
         /* if its not a whitespace, this *could* be the last character */
-        if ( !isspace (c) )
+        if ( !isspace ((unsigned char)c) )
         {
             end = output;
         }
@@ -1050,14 +1050,14 @@ gchar * trim_nocopy (gchar * s)
     gchar * end = NULL;
 
     /* skip spaces at start */
-    while (*start && isspace (*start) )
+    while (*start && isspace ((unsigned char)*start) )
         ++start;
 
     /* iterate over the rest remebering last non-whitespace */
     char *i = start;
     while (*i)
     {
-        if ( !isspace (* (i++) ) )
+        if ( !isspace ((unsigned char) * (i++) ) )
             end = i;
     }

**Comment by sahib** [comment]
Hi, thanks for the notice.

The formatting is quite broken on here.
Can you put it in a pastebin (like https://gist.github.com/ e.g.) please?

**Comment by iamleot** [comment]
Hello Chris,

"Chris P." writes:
> Hi, thanks for the notice.
> 
> The formatting is quite broken on here.
> Can you put it in a pastebin (like https://gist.github.com/ e.g.) please?
Of course!:

 http://sprunge.us/MZMC


Ciao,
L.

**Comment by sahib** [comment]
Thanks, applied as of 68962c8720b409adc4cb890c8146df5f8504bfd8.
It will be included in the next release.
