### ISSUE TITLE
glyrc uses wrong image url from slothradio

### ISSUE THREAD

**Issue by SamHawkens** [sahib/glyr#63]
I am getting totally wrong cover images when downloading from slothradio. 
glyr release 1.0.8
Please try:
glyrc cover --album "thriller" --artist "michael jackson" --from "slothradio" -lang us -v 4

gets
---- Triggering: slothradio 
* About to connect() to www.slothradio.com port 80 (#0)
*   Trying 216.119.132.66... * Connected to www.slothradio.com (216.119.132.66) port 80 (#0)
> GET /covers/?adv=1&artist=michael jackson&album=thriller&imgsize=x&locale=us&sort=salesrank HTTP/1.1

and actually fetches some lullaby CD cover :-)
///// ITEM #1 /////
WRITE to './michael jackson_thriller__cover_1.jpeg'
FROM: <http://ecx.images-amazon.com/images/I/51fT-bSQplL.jpg>

when I enter this url directly in my browser I see the correct image:
slothradio.com/covers/?adv=1&artist=michael jackson&album=thriller&imgsize=x&locale=us&sort=salesrank

The error is not specific to this CD, I always get wrong covers from slothradio.

**Comment by sahib** [comment]
Thanks, should be fixed as of e871de0afbb463a4a72a1c6fd97e74483d1a847b.

**Comment by SamHawkens** [comment]
Great, it works now!

Thanks a lot. Never seen anyone fix a problem that fast :-)
