### ISSUE TITLE
lyrics completely broke

### ISSUE THREAD

**Issue by mabushey** [sahib/glyr#78]
Issue #1: The example from --help is missing `title`:
```
glyrc --help
...
glyrc lyrics -a A -b B --cache /tmp # Write found items to cache; create it if not existant
...

glyrc lyrics -a A -b B --cache /tmp
Songname is required for this getter
Error: Insufficient data supplied for this getter
```
Issue #2: Adding title results in garbage output:
```
glyrc lyrics --artist Rush --album "Fly by night"  --title Anthem
- Artist   : rush
- Album    : fly by night
- Title    : anthem
- Language : us
- Type     : lyrics

---- Triggering: musictree 
---- Triggering: local 
---- Triggering: lyricswiki 
---- 

///// ITEM #1 /////
WRITE to './Rush_Fly by night_Anthem_lyrics_1.txt'
FROM: <http://lyrics.wikia.com/Rush:Anthem>
PROV: lyricswiki
SIZE: 289 Bytes
MSUM: 704b5e08e76507e85af55d4040417a28
TYPE: songtext
SAFE: No
RATE: 0
STMP: 0.000000
DATA: 
Categories:


Song






Bronze Songs
...
```

```
head Rush_Fly\ by\ night_Anthem_lyrics_1.txt
Categories:


Song






```

**Comment by KabbAmine** [comment]
Same thing here (Using [lyvi](https://github.com/ok100/lyvi)).
I've tried the version shipped with my distribution and compiled the sources, and same issue in both of them.

OS: `Xubuntu 16.04`
`glyr 1.0.8`
`libglyr 1.0.8`

For example, ` glyrc lyrics -a "disturbed" -t "just stop` gives:

```sh
- Artist   : disturbed
- Title    : just stop
- Language : fr
- Type     : lyrics

---- Triggering: musictree
---- Triggering: local
---- Triggering: lyricswiki
----

///// ITEM #1 /////
WRITE to './disturbed__just stop_lyrics_1.txt'
FROM: <http://lyrics.wikia.com/Disturbed:Just_Stop>
PROV: lyricswiki
SIZE: 231 Bytes
MSUM: 156806c3b955fa5447c3435c44395240
TYPE: songtext
SAFE: No
RATE: 0
STMP: 0,000000
DATA:
Categories:


Song






Green Songs






Language/English






Songs by Disturbed






Songs J






ITunes/Song






Amazon/Song






Spotify/Song






Allmusic/Song






MusicBrainz/Song






Add category




Cancel
Save

////////////////////
# => 1 item in total.
```

And as expected, no lyrics in `disturbed__just stop_lyrics_1.txt`:

 ```
Categories:


Song






Green Songs






Language/English






Songs by Disturbed






Songs J






ITunes/Song






Amazon/Song






Spotify/Song






Allmusic/Song






MusicBrainz/Song






Add category




Cancel
Save
```

**Comment by iamleot** [comment]
Hello Michael!

Michael Bushey writes:
> Issue #1: The example from --help is missing `title`:
> ```
> glyrc --help
> ...
> glyrc lyrics -a A -b B --cache /tmp # Write found items to cache; create it if not existant
> ...
> 
> glyrc lyrics -a A -b B --cache /tmp
> Songname is required for this getter
> Error: Insufficient data supplied for this getter
> ```
Nice spotted, this can be probably easily fixable modifying the usage
message in src/glyrc/glyrc.c:320 just adding a `-t T` (and maybe getting
rid of `-b` that is more rarely needed).

> Issue #2: Adding title results in garbage output:
> ```
> glyrc lyrics --artist Rush --album "Fly by night"  --title Anthem
> - Artist   : rush
> - Album    : fly by night
> - Title    : anthem
> - Language : us
> - Type     : lyrics
> 
> ---- Triggering: musictree 
> ---- Triggering: local 
> ---- Triggering: lyricswiki 
> ---- 
> [...]
This should be fixed in glyr-1.0.9 (latest stable release) via
issue #69. Can you please try it and/or ask the distribution maintainer
to update the glyr package?


Thank you!

**Comment by KabbAmine** [comment]
> This should be fixed in glyr-1.0.9 (latest stable release) via issue #69. Can you please try it and/or ask the distribution maintainer to update the glyr package?

My bad, as for me `1.0.9` solves the problem. I maybe had a problem with the compilation.

**Comment by Corwin7** [comment]
I compiled version 1.0.9 and the lyrics is working now. Thanks!  Any idea when fetching album art >300 pixels is going to work?

**Comment by mabushey** [comment]
I compiled version 1.0.9 and the lyrics is working now. Thanks! Any idea when fetching album art >300 pixels is going to work?
